clear
text="$1"
endText="$2"
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $text . . . /
echo $text . . . _
echo $text . . . |
echo $text . . . \
echo $text . . . |
echo $endText sucessful.